version: "3.7"

services:
  yosys:
    container_name: yosys
    # build: .
    image: ghcr.io/gdnmhr/contractgen:latest
    volumes:
      - .:/home/yosys/resources
      - ../../..:/home/yosys/project
    #entrypoint: /bin/bash
    entrypoint: /home/yosys/resources/run.sh
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
